# Generated by Django 2.2.24 on 2021-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20211204_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купоны', 'verbose_name_plural': 'Купон'},
        ),
    ]
