# Generated by Django 2.2.24 on 2021-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211201_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
